---
- hosts: kuberntes_node
  become: true
  become_user: root

  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Creating multiple files
      ansible.builtin.shell: 
        cmd: |
          curl -sfL https://get.k3s.io | K3S_URL=https://REPLACE_ME_MASTER_IP:6443 K3S_TOKEN=REPLACE_ME_TOKEN sh -


    - name: checking service status
      command: systemctl status "{{ item }}"
      with_items:
      - k3s-agent
      register: result

    - name: showing report
      debug:
      var: result