---
- hosts: kuberntes_node
  become: true
  become_user: root

  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name : Install multiple packages
      apt: name={{ item }} state=latest update_cache=true
      loop: [git, wget, unzip, curl, ssh, jq, apt-transport-https, apache2-utils] 


    - name: Creating multiple files
      shell: curl -sfL https://get.k3s.io | K3S_URL=https://REPLACE_ME_MASTER_IP:6443 K3S_TOKEN=REPLACE_ME_TOKEN sh -
      args:
        warn: no

    - name: Check for apache status
      shell: systemctl status k3s-agent.service
      args:
        warn: no