apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rootca-selfsigned-crt
  namespace: cert-manager
spec:
  isCA: true
  duration: 8760 # 1 year
  renewBefore: 360h # 15d
  commonName: CERT_MANAGER_LOCAL_DOMAIN_NAME
  secretName: rootca-selfsigned-crt
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local-domain-self-signed
  namespace: cert-manager
spec:
  ca:
    secretName: rootca-selfsigned-crt