---
- hosts: kuberntes_node
  become: true
  become_user: root

  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Creating a file For Root Ansible
      copy:
        dest: "/etc/sudoers.d/ANSIBLE_NODE_USER"
        content: |
          ANSIBLE_NODE_USER ALL=(ALL) NOPASSWD: ALL