---
- hosts: kuberntes_node
  become: true
  become_user: root

  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name : Install multiple packages
      apt: name={{ item }} state=latest update_cache=true
      loop: [git, wget, unzip, curl, ssh, jq, apt-transport-https, apache2-utils, open-iscsi, nfs-common] 


    - name: Install Kubernetes on nodes
      shell: curl -sfL https://get.k3s.io | K3S_URL=https://K3S_URL_IP:6443 K3S_TOKEN=K3S_TOKEN_KEY INSTALL_K3S_VERSION="INSTALL_K3S_VERSION_NUM" sh -s - server --docker --write-kubeconfig-mode 644 $K3S_EXTRA_ARG
      args:
        warn: no

    # - name: Check for apache status
    #   shell: systemctl status k3s-agent.service
    #   args:
    #     warn: no